//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDVision.Business.NavicureService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityHeaderType", Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService")]
    [System.SerializableAttribute()]
    public partial class SecurityHeaderType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string originatingIdentifierField;
        
        private string submitterIdentifierField;
        
        private string submitterPasswordField;
        
        private long submissionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string originatingIdentifier {
            get {
                return this.originatingIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.originatingIdentifierField, value) != true)) {
                    this.originatingIdentifierField = value;
                    this.RaisePropertyChanged("originatingIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string submitterIdentifier {
            get {
                return this.submitterIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.submitterIdentifierField, value) != true)) {
                    this.submitterIdentifierField = value;
                    this.RaisePropertyChanged("submitterIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string submitterPassword {
            get {
                return this.submitterPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.submitterPasswordField, value) != true)) {
                    this.submitterPasswordField = value;
                    this.RaisePropertyChanged("submitterPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long submissionId {
            get {
                return this.submissionIdField;
            }
            set {
                if ((this.submissionIdField.Equals(value) != true)) {
                    this.submissionIdField = value;
                    this.RaisePropertyChanged("submissionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitRequestType", Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService")]
    [System.SerializableAttribute()]
    public partial class SubmitRequestType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string timeoutField;
        
        private string transactionTypeField;
        
        private string submittedAnsiVersionField;
        
        private string resultAnsiVersionField;
        
        private string submitterSubmissionIdField;
        
        private string processingOptionField;
        
        private string payloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string timeout {
            get {
                return this.timeoutField;
            }
            set {
                if ((object.ReferenceEquals(this.timeoutField, value) != true)) {
                    this.timeoutField = value;
                    this.RaisePropertyChanged("timeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionTypeField, value) != true)) {
                    this.transactionTypeField = value;
                    this.RaisePropertyChanged("transactionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string submittedAnsiVersion {
            get {
                return this.submittedAnsiVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.submittedAnsiVersionField, value) != true)) {
                    this.submittedAnsiVersionField = value;
                    this.RaisePropertyChanged("submittedAnsiVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string resultAnsiVersion {
            get {
                return this.resultAnsiVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.resultAnsiVersionField, value) != true)) {
                    this.resultAnsiVersionField = value;
                    this.RaisePropertyChanged("resultAnsiVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string submitterSubmissionId {
            get {
                return this.submitterSubmissionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.submitterSubmissionIdField, value) != true)) {
                    this.submitterSubmissionIdField = value;
                    this.RaisePropertyChanged("submitterSubmissionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string processingOption {
            get {
                return this.processingOptionField;
            }
            set {
                if ((object.ReferenceEquals(this.processingOptionField, value) != true)) {
                    this.processingOptionField = value;
                    this.RaisePropertyChanged("processingOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string payload {
            get {
                return this.payloadField;
            }
            set {
                if ((object.ReferenceEquals(this.payloadField, value) != true)) {
                    this.payloadField = value;
                    this.RaisePropertyChanged("payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseType", Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService")]
    [System.SerializableAttribute()]
    public partial class ResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string transactionTypField;
        
        private string submitterSubmissionIdField;
        
        private string systemSubmissionIdField;
        
        private string submittedAnsiVersionField;
        
        private string resultAnsiVersionField;
        
        private string payloadField;
        
        private string processedRealTimeField;
        
        private MDVision.Business.NavicureService.StatusHeaderType statusHeaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string transactionTyp {
            get {
                return this.transactionTypField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionTypField, value) != true)) {
                    this.transactionTypField = value;
                    this.RaisePropertyChanged("transactionTyp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string submitterSubmissionId {
            get {
                return this.submitterSubmissionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.submitterSubmissionIdField, value) != true)) {
                    this.submitterSubmissionIdField = value;
                    this.RaisePropertyChanged("submitterSubmissionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string systemSubmissionId {
            get {
                return this.systemSubmissionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.systemSubmissionIdField, value) != true)) {
                    this.systemSubmissionIdField = value;
                    this.RaisePropertyChanged("systemSubmissionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string submittedAnsiVersion {
            get {
                return this.submittedAnsiVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.submittedAnsiVersionField, value) != true)) {
                    this.submittedAnsiVersionField = value;
                    this.RaisePropertyChanged("submittedAnsiVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string resultAnsiVersion {
            get {
                return this.resultAnsiVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.resultAnsiVersionField, value) != true)) {
                    this.resultAnsiVersionField = value;
                    this.RaisePropertyChanged("resultAnsiVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string payload {
            get {
                return this.payloadField;
            }
            set {
                if ((object.ReferenceEquals(this.payloadField, value) != true)) {
                    this.payloadField = value;
                    this.RaisePropertyChanged("payload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string processedRealTime {
            get {
                return this.processedRealTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.processedRealTimeField, value) != true)) {
                    this.processedRealTimeField = value;
                    this.RaisePropertyChanged("processedRealTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public MDVision.Business.NavicureService.StatusHeaderType statusHeader {
            get {
                return this.statusHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.statusHeaderField, value) != true)) {
                    this.statusHeaderField = value;
                    this.RaisePropertyChanged("statusHeader");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusHeaderType", Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService")]
    [System.SerializableAttribute()]
    public partial class StatusHeaderType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        private bool requestProcessedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.statusCodeField, value) != true)) {
                    this.statusCodeField = value;
                    this.RaisePropertyChanged("statusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.statusMessageField, value) != true)) {
                    this.statusMessageField = value;
                    this.RaisePropertyChanged("statusMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool requestProcessed {
            get {
                return this.requestProcessedField;
            }
            set {
                if ((this.requestProcessedField.Equals(value) != true)) {
                    this.requestProcessedField = value;
                    this.RaisePropertyChanged("requestProcessed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService", ConfigurationName="NavicureService.NavicureSubmissionService")]
    public interface NavicureSubmissionService {
        
        // CODEGEN: Generating message contract since the operation submitAnsiSingle is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="submitAnsiSingle", ReplyAction="*")]
        MDVision.Business.NavicureService.submitAnsiSingleResponse submitAnsiSingle(MDVision.Business.NavicureService.submitAnsiSingleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitAnsiSingleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService")]
        public MDVision.Business.NavicureService.SecurityHeaderType SecurityHeaderElement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService", Order=0)]
        public MDVision.Business.NavicureService.SubmitRequestType SubmitAnsiSingleRequestElement;
        
        public submitAnsiSingleRequest() {
        }
        
        public submitAnsiSingleRequest(MDVision.Business.NavicureService.SecurityHeaderType SecurityHeaderElement, MDVision.Business.NavicureService.SubmitRequestType SubmitAnsiSingleRequestElement) {
            this.SecurityHeaderElement = SecurityHeaderElement;
            this.SubmitAnsiSingleRequestElement = SubmitAnsiSingleRequestElement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitAnsiSingleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService", Order=0)]
        public MDVision.Business.NavicureService.ResponseType SubmitAnsiSingleResponseElement;
        
        public submitAnsiSingleResponse() {
        }
        
        public submitAnsiSingleResponse(MDVision.Business.NavicureService.ResponseType SubmitAnsiSingleResponseElement) {
            this.SubmitAnsiSingleResponseElement = SubmitAnsiSingleResponseElement;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NavicureSubmissionServiceChannel : MDVision.Business.NavicureService.NavicureSubmissionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NavicureSubmissionServiceClient : System.ServiceModel.ClientBase<MDVision.Business.NavicureService.NavicureSubmissionService>, MDVision.Business.NavicureService.NavicureSubmissionService {
        
        public NavicureSubmissionServiceClient() {
        }
        
        public NavicureSubmissionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NavicureSubmissionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NavicureSubmissionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NavicureSubmissionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDVision.Business.NavicureService.submitAnsiSingleResponse MDVision.Business.NavicureService.NavicureSubmissionService.submitAnsiSingle(MDVision.Business.NavicureService.submitAnsiSingleRequest request) {
            return base.Channel.submitAnsiSingle(request);
        }
        
        public MDVision.Business.NavicureService.ResponseType submitAnsiSingle(MDVision.Business.NavicureService.SecurityHeaderType SecurityHeaderElement, MDVision.Business.NavicureService.SubmitRequestType SubmitAnsiSingleRequestElement) {
            MDVision.Business.NavicureService.submitAnsiSingleRequest inValue = new MDVision.Business.NavicureService.submitAnsiSingleRequest();
            inValue.SecurityHeaderElement = SecurityHeaderElement;
            inValue.SubmitAnsiSingleRequestElement = SubmitAnsiSingleRequestElement;
            MDVision.Business.NavicureService.submitAnsiSingleResponse retVal = ((MDVision.Business.NavicureService.NavicureSubmissionService)(this)).submitAnsiSingle(inValue);
            return retVal.SubmitAnsiSingleResponseElement;
        }
    }
}
