//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDVision.IEHR.AlphaIIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://services.alphaii.net/", ConfigurationName="AlphaIIService.ScrubMethodSoap")]
    public interface ScrubMethodSoap {
        
        // CODEGEN: Generating message contract since element name EDIServer from namespace https://services.alphaii.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alphaii.net/Scrub", ReplyAction="*")]
        MDVision.IEHR.AlphaIIService.ScrubResponse Scrub(MDVision.IEHR.AlphaIIService.ScrubRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alphaii.net/Scrub", ReplyAction="*")]
        System.Threading.Tasks.Task<MDVision.IEHR.AlphaIIService.ScrubResponse> ScrubAsync(MDVision.IEHR.AlphaIIService.ScrubRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScrubRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Scrub", Namespace="https://services.alphaii.net/", Order=0)]
        public MDVision.IEHR.AlphaIIService.ScrubRequestBody Body;
        
        public ScrubRequest() {
        }
        
        public ScrubRequest(MDVision.IEHR.AlphaIIService.ScrubRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://services.alphaii.net/")]
    public partial class ScrubRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EDIServer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Submitter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PW;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RPTType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EDIData;
        
        public ScrubRequestBody() {
        }
        
        public ScrubRequestBody(string EDIServer, string Submitter, string UID, string PW, string RPTType, string EDIData) {
            this.EDIServer = EDIServer;
            this.Submitter = Submitter;
            this.UID = UID;
            this.PW = PW;
            this.RPTType = RPTType;
            this.EDIData = EDIData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScrubResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScrubResponse", Namespace="https://services.alphaii.net/", Order=0)]
        public MDVision.IEHR.AlphaIIService.ScrubResponseBody Body;
        
        public ScrubResponse() {
        }
        
        public ScrubResponse(MDVision.IEHR.AlphaIIService.ScrubResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://services.alphaii.net/")]
    public partial class ScrubResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ScrubResult;
        
        public ScrubResponseBody() {
        }
        
        public ScrubResponseBody(string ScrubResult) {
            this.ScrubResult = ScrubResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScrubMethodSoapChannel : MDVision.IEHR.AlphaIIService.ScrubMethodSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScrubMethodSoapClient : System.ServiceModel.ClientBase<MDVision.IEHR.AlphaIIService.ScrubMethodSoap>, MDVision.IEHR.AlphaIIService.ScrubMethodSoap {
        
        public ScrubMethodSoapClient() {
        }
        
        public ScrubMethodSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScrubMethodSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScrubMethodSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScrubMethodSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDVision.IEHR.AlphaIIService.ScrubResponse MDVision.IEHR.AlphaIIService.ScrubMethodSoap.Scrub(MDVision.IEHR.AlphaIIService.ScrubRequest request) {
            return base.Channel.Scrub(request);
        }
        
        public string Scrub(string EDIServer, string Submitter, string UID, string PW, string RPTType, string EDIData) {
            MDVision.IEHR.AlphaIIService.ScrubRequest inValue = new MDVision.IEHR.AlphaIIService.ScrubRequest();
            inValue.Body = new MDVision.IEHR.AlphaIIService.ScrubRequestBody();
            inValue.Body.EDIServer = EDIServer;
            inValue.Body.Submitter = Submitter;
            inValue.Body.UID = UID;
            inValue.Body.PW = PW;
            inValue.Body.RPTType = RPTType;
            inValue.Body.EDIData = EDIData;
            MDVision.IEHR.AlphaIIService.ScrubResponse retVal = ((MDVision.IEHR.AlphaIIService.ScrubMethodSoap)(this)).Scrub(inValue);
            return retVal.Body.ScrubResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MDVision.IEHR.AlphaIIService.ScrubResponse> MDVision.IEHR.AlphaIIService.ScrubMethodSoap.ScrubAsync(MDVision.IEHR.AlphaIIService.ScrubRequest request) {
            return base.Channel.ScrubAsync(request);
        }
        
        public System.Threading.Tasks.Task<MDVision.IEHR.AlphaIIService.ScrubResponse> ScrubAsync(string EDIServer, string Submitter, string UID, string PW, string RPTType, string EDIData) {
            MDVision.IEHR.AlphaIIService.ScrubRequest inValue = new MDVision.IEHR.AlphaIIService.ScrubRequest();
            inValue.Body = new MDVision.IEHR.AlphaIIService.ScrubRequestBody();
            inValue.Body.EDIServer = EDIServer;
            inValue.Body.Submitter = Submitter;
            inValue.Body.UID = UID;
            inValue.Body.PW = PW;
            inValue.Body.RPTType = RPTType;
            inValue.Body.EDIData = EDIData;
            return ((MDVision.IEHR.AlphaIIService.ScrubMethodSoap)(this)).ScrubAsync(inValue);
        }
    }
}
