

Clinical_PreviewReportHeaderTemplate = {
    bIsFirstLoad: true,
    params: [],
    specialityCheckedIds: [],
    providerCheckedIds: [],
    SpecialtyIds: '',
    ProviderIds: '',
    //Start || 9 August, 2016 || Talha Tanweer ||
    Load: function (params) {
        Clinical_PreviewReportHeaderTemplate.params = params;
        //  Clinical_PreviewReportHeaderTemplate.patientId = $("div#PatientProfile #hfPatientId").val();
        //  Clinical_PreviewReportHeaderTemplate.params.mode = "Add";

        if (Clinical_PreviewReportHeaderTemplate.params.PanelID != 'pnlPreviewReportHeaderTemplate') {
            Clinical_PreviewReportHeaderTemplate.params.PanelID = Clinical_PreviewReportHeaderTemplate.params.PanelID + ' #pnlPreviewReportHeaderTemplate';
        } else {
            Clinical_PreviewReportHeaderTemplate.params.PanelID = 'pnlPreviewReportHeaderTemplate';
        }


        //Clinical_PreviewReportHeaderTemplate.isEntitySelected();
        ////////   if (Clinical_PreviewReportHeaderTemplate.bIsFirstLoad) {
        ////////       Clinical_PreviewReportHeaderTemplate.bIsFirstLoad = false;
        ////////       var self = $('#' + Clinical_PreviewReportHeaderTemplate.params.PanelID);
        ////////       var data = "EntityId=";
        ////////
        ////////     //  Clinical_PreviewReportHeaderTemplate.TemplateTagsLookupsLoad();
        ////////   } else { }

        var practiceTag = params["PracticeTags"];
        var patientTag = params["PatientTags"];
        var providerTag = params["ProviderTags"];
        var Footer_generatedBy = params["FooterGeneratedBy"];
        var HeaderLogoImgSrc = params["HeaderLogo"];
        Clinical_PreviewReportHeaderTemplate.DisplayTagsInPreview(practiceTag, patientTag, providerTag, Footer_generatedBy, HeaderLogoImgSrc);

    },




    //Author: Talha Tanweer
    //Date  : 09/08/2016
    UnLoad: function (caller) {

        var parentContolId = "Clinical_AddReportHeaderTemplate";
        var controlId = "Clinical_PreviewReportHeaderTemplate";
        UnloadActionPan(parentContolId, controlId);
    },

    //Author: Talha Tanweer
    //Date  : 09/08/2016
    DisplayTagsInPreview: function (practiceTag, patientTag, providerTag, Footer_generatedBy, HeaderLogoImgSrc) {

        $("#" + Clinical_PreviewReportHeaderTemplate.params.PanelID + " #divPracticeTags").html(practiceTag);
        $("#" + Clinical_PreviewReportHeaderTemplate.params.PanelID + " #divPatientTags ").html(patientTag);
        $("#" + Clinical_PreviewReportHeaderTemplate.params.PanelID + " #divProviderTags").html(providerTag);

        if (HeaderLogoImgSrc != "") {
            $("#" + Clinical_PreviewReportHeaderTemplate.params.PanelID + " #dvimgReportHeaderLogoPreview").show();
            $("#" + Clinical_PreviewReportHeaderTemplate.params.PanelID + " #imgReportHeaderLogoPreview").attr("src", HeaderLogoImgSrc);
        }




        if (Footer_generatedBy != null || Footer_generatedBy != undefined || Footer_generatedBy != "") {
            var footerText = " Generated by: " + Footer_generatedBy+" <span class='pull-right pr-md'>Page 1 of 1</span>";
            $("#" + Clinical_PreviewReportHeaderTemplate.params.PanelID + " #lblfooterGeneratedByPreview").html(footerText);
        }

    },








}