//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDVision.IEHR.NavicureService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService", ConfigurationName="NavicureService.NavicureSubmissionService")]
    public interface NavicureSubmissionService {
        
        // CODEGEN: Generating message contract since the operation submitAnsiSingle is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="submitAnsiSingle", ReplyAction="*")]
        MDVision.IEHR.NavicureService.submitAnsiSingleResponse submitAnsiSingle(MDVision.IEHR.NavicureService.submitAnsiSingleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="submitAnsiSingle", ReplyAction="*")]
        System.Threading.Tasks.Task<MDVision.IEHR.NavicureService.submitAnsiSingleResponse> submitAnsiSingleAsync(MDVision.IEHR.NavicureService.submitAnsiSingleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitAnsiSingleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService")]
        public MDVision.Business.NavicureService.SecurityHeaderType SecurityHeaderElement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService", Order=0)]
        public MDVision.Business.NavicureService.SubmitRequestType SubmitAnsiSingleRequestElement;
        
        public submitAnsiSingleRequest() {
        }
        
        public submitAnsiSingleRequest(MDVision.Business.NavicureService.SecurityHeaderType SecurityHeaderElement, MDVision.Business.NavicureService.SubmitRequestType SubmitAnsiSingleRequestElement) {
            this.SecurityHeaderElement = SecurityHeaderElement;
            this.SubmitAnsiSingleRequestElement = SubmitAnsiSingleRequestElement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitAnsiSingleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.navicure.com/2009/11/NavicureSubmissionService", Order=0)]
        public MDVision.Business.NavicureService.ResponseType SubmitAnsiSingleResponseElement;
        
        public submitAnsiSingleResponse() {
        }
        
        public submitAnsiSingleResponse(MDVision.Business.NavicureService.ResponseType SubmitAnsiSingleResponseElement) {
            this.SubmitAnsiSingleResponseElement = SubmitAnsiSingleResponseElement;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NavicureSubmissionServiceChannel : MDVision.IEHR.NavicureService.NavicureSubmissionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NavicureSubmissionServiceClient : System.ServiceModel.ClientBase<MDVision.IEHR.NavicureService.NavicureSubmissionService>, MDVision.IEHR.NavicureService.NavicureSubmissionService {
        
        public NavicureSubmissionServiceClient() {
        }
        
        public NavicureSubmissionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NavicureSubmissionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NavicureSubmissionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NavicureSubmissionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDVision.IEHR.NavicureService.submitAnsiSingleResponse MDVision.IEHR.NavicureService.NavicureSubmissionService.submitAnsiSingle(MDVision.IEHR.NavicureService.submitAnsiSingleRequest request) {
            return base.Channel.submitAnsiSingle(request);
        }
        
        public MDVision.Business.NavicureService.ResponseType submitAnsiSingle(MDVision.Business.NavicureService.SecurityHeaderType SecurityHeaderElement, MDVision.Business.NavicureService.SubmitRequestType SubmitAnsiSingleRequestElement) {
            MDVision.IEHR.NavicureService.submitAnsiSingleRequest inValue = new MDVision.IEHR.NavicureService.submitAnsiSingleRequest();
            inValue.SecurityHeaderElement = SecurityHeaderElement;
            inValue.SubmitAnsiSingleRequestElement = SubmitAnsiSingleRequestElement;
            MDVision.IEHR.NavicureService.submitAnsiSingleResponse retVal = ((MDVision.IEHR.NavicureService.NavicureSubmissionService)(this)).submitAnsiSingle(inValue);
            return retVal.SubmitAnsiSingleResponseElement;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MDVision.IEHR.NavicureService.submitAnsiSingleResponse> MDVision.IEHR.NavicureService.NavicureSubmissionService.submitAnsiSingleAsync(MDVision.IEHR.NavicureService.submitAnsiSingleRequest request) {
            return base.Channel.submitAnsiSingleAsync(request);
        }
        
        public System.Threading.Tasks.Task<MDVision.IEHR.NavicureService.submitAnsiSingleResponse> submitAnsiSingleAsync(MDVision.Business.NavicureService.SecurityHeaderType SecurityHeaderElement, MDVision.Business.NavicureService.SubmitRequestType SubmitAnsiSingleRequestElement) {
            MDVision.IEHR.NavicureService.submitAnsiSingleRequest inValue = new MDVision.IEHR.NavicureService.submitAnsiSingleRequest();
            inValue.SecurityHeaderElement = SecurityHeaderElement;
            inValue.SubmitAnsiSingleRequestElement = SubmitAnsiSingleRequestElement;
            return ((MDVision.IEHR.NavicureService.NavicureSubmissionService)(this)).submitAnsiSingleAsync(inValue);
        }
    }
}
