using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MDVision.IEHR.Model.Billing.Payments
{
    public class PaymentPostingModel
    {
        public string CommandType { get; set; }
        public string PatientAccount { get; set; }
        public string PatientName { get; set; }
        public string ClaimNumber { get; set; }
        public string IncludeSecondaryClaim { get; set; }
        public string CaseNumber { get; set; }
        public string AmountReceived { get; set; }
        public string ClaimType { get; set; }
        public string DateDOSFrom { get; set; }
        public string DateDOSTo { get; set; }
        public string Insurance { get; set; }
        public string Patient { get; set; }
        public string Copayment { get; set; }
        public string ZeroPayment { get; set; }
        public string Payment { get; set; }
        public string Payment_txt { get; set; }
        public string Recoupment { get; set; }
        public string Facility { get; set; }
        public string Provider { get; set; }
        public string PaymentBatch { get; set; }
        public string DatePaid { get; set; }
        public string PaymentType { get; set; }
        public string PaymentMode { get; set; }
        public string checkNumber { get; set; }
        public string checkDate { get; set; }
        public string creditCardType { get; set; }
        public string cardNumber { get; set; }
        public string expiryDate { get; set; }
        public string AdvancePayment { get; set; }
        public string InsuranceAllowed { get; set; }
        public string InsurancePaid { get; set; }
        public string InsurancePaidAccount { get; set; }
        public string InsuranceWriteoff { get; set; }
        public string InsuranceWriteoffAccount { get; set; }
        public string Balance { get; set; }
        public string RemittanceCode { get; set; }
        public string ICN_DCN { get; set; }
        public string Copay { get; set; }
        public string InsuranceCoinsurance { get; set; }
        public string InsuranceDeductables { get; set; }
        public string InsurancePatientResponsibilityr { get; set; }
        public string RadInsuranceNextResponsibility { get; set; }
        public string RadPatientNextResponsibility { get; set; }
        public string NextInsuranceInsurancePlan { get; set; }
        public string PlanPriority { get; set; }
        public string InsuranceCrossOve { get; set; }
        public string PrintOnPatientStatement { get; set; }
        public string InsuranceComments { get; set; }
        public string PatientPaid { get; set; }
        public string PatientPaidAccount { get; set; }
        public string PatientDiscount { get; set; }
        public string PatientDiscountAccount { get; set; }
        public string PatientBalance { get; set; }
        public string Patientcoinsurance { get; set; }
        public string Patientdeductables { get; set; }
        public string PatientPatientResponsibility { get; set; }
        public string RadPatNextResponsibility { get; set; }
        public string RadPatNextResponsibility_txt { get; set; }
        public string RadPatNextResponsibilityIns { get; set; }
        public string NextPatientInsurancePlan { get; set; }
        public string PatPrintOnPatientStatement { get; set; }
        public string PatientComments { get; set; }
        public string CopaymentPaid { get; set; }
        public string CopaymentPaidAccount { get; set; }
        public string CopaymentDiscount { get; set; }
        public string CopaymentDiscountAccount { get; set; }
        public string CopaymentBalance { get; set; }
        public string CopayAmount { get; set; }
        public string RadCopayNextResponsibility { get; set; }
        public string CopayPrintOnPatientStatement { get; set; }
        public string ZeroPayPrintOnPatientStatement { get; set; }
        public string ZeroPaymentComments { get; set; }
        public string CopaymentComments { get; set; }
        public string RecoupmentAllowed { get; set; }
        public string RecoupmentPaid { get; set; }
        public string RecoupmentPaidAccount { get; set; }
        public string RecoupmentWriteoff { get; set; }
        public string RecoupmentWriteoffAccount { get; set; }
        public string RecoupmentRemittanceCode { get; set; }
        public string RecoupmentCopay { get; set; }
        public string RecoupmentICN_DCN { get; set; }
        public string RecoupmentCoinsurance { get; set; }
        public string RecoupmentDeductables { get; set; }
        public string RecoupmentPatientResponsibility { get; set; }
        public string RadRecoupmentNextResponsibility { get; set; }
        public string RadRecoupmentNextResponsibilityIns { get; set; }
        public string RecoupmentInsPrintOnPatientStatement { get; set; }
        public string InsuranceCopay { get; set; }
        public string RecoupmentComments { get; set; }
        public string HiddenFieldChargeId { get; set; }
        public string ChargeTotalBalance { get; set; }
        public string InsuranceCharge { get; set; }
        public string PatientCharge { get; set; }
        public string CopayCharge { get; set; }
        public string InsuranceBalance { get; set; }
        public string HiddenFieldPatientBalance { get; set; }
        public string CopayBalance { get; set; }
        public string HiddenFieldVisitId { get; set; }
        public string TransferLedgerAccountId { get; set; }
        public string InsuranceToPatientLedgerAccountId { get; set; }
        public string PatienttoTransferLedgerAccountId { get; set; }
        public string ChargeFee { get; set; }
        public string HiddenFieldPaymentBatch { get; set; }
        public string AdvanceBalance { get; set; }
        public string InsurancePlanId { get; set; }
        public string InsurancePlanName { get; set; }
        public string IsDenied { get; set; }
        public string PatientId { get; set; }
        public string CaseId { get; set; }
        public string FacilityId { get; set; }
        public string ProviderId { get; set; }
        public string AdvancePaymentId { get; set; }
        public string PageNumber { get; set; }
        public string RowsPerPage { get; set; }
        public string ChargeId { get; set; }
        public string VisitId { get; set; }
        public string PatNextResPatient { get; set; }
        public string PatNextResInsurance { get; set; }
        public string CopayNextResInsurance { get; set; }
        public string RecoupNextResInsurance { get; set; }
        public string RecoupNextResPatient { get; set; }
        public string InsNextResPatient { get; set; }
        public string InsNextResInsurance { get; set; }
        public string PatientInsurancePlanId { get; set; }
        public string InsurancePlanPriority { get; set; }
        public string ClaimErroredId { get; set; }
        public string IncludeVoidedClaims { get; set; }
        public string RecoupmentNextInsurancePlanId { get; set; }
        
    }
}